language: php

php:
  - 8.0
  - 8.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.3
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
